CREATE PROCEDURE DB2INST1.SEARCH_CUSTOMERS_BY_NAME (
    IN P_NAME VARCHAR(255)
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
    DECLARE C1 CURSOR WITH RETURN FOR
        SELECT ID, NAME, EMAIL, AGE
        FROM DB2INST1.CUSTOMERS
        WHERE NAME LIKE '%' || P_NAME || '%';
    OPEN C1;
END;
